services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ws
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"  # Проброс порта на хост
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ws"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ./web:/app/web
    environment:
      - HOST=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy