services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ws
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ws"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "postgres://postgres:12345678@postgres:5432/ws?sslmode=disable",
      "up"
    ]

  app:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - ./web:/app/web
    environment:
      - HOST=0.0.0.0
    depends_on:
      migrate:
        condition: service_completed_successfully
